name: dextraservice
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  location: ^2.3.5
  image_picker: ^0.6.0+1
  google_maps_flutter: ^0.5.19+2
  http: 0.12.0+1
  sqflite: ^1.1.6+5
  flutter_money_formatter: ^0.8.2
  path_provider: ^1.3.0
  firebase_messaging: ^5.1.4
  shared_preferences: ^0.4.3
  progress_dialog: ^1.1.0+1
  shimmer: ^1.0.0
  intro_views_flutter: "^2.6.0"
  geolocator: ^5.1.1+1
  latlong: ^0.6.1
  rxdart: ^0.22.1
  cached_network_image: ^1.1.1
  pin_code_text_field: ^1.4.0
  flutter_slidable: "^0.2.0"
  flutter_spinkit: ^3.1.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1
  json_serializable: ^3.0.0

  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - assets/icon/book.png
    - assets/icon/camera.png
    - assets/icon/fashion.png
    - assets/icon/food.png
    - assets/icon/game.png
    - assets/icon/handphone.png
    - assets/icon/health.png
    - assets/icon/mesin.png
    - assets/icon/otomotif.png
    - assets/icon/pc.png
    - assets/icon/sport.png
    - assets/icon/ticket.png
    - assets/icon/truck.png
    - assets/icon/chat.png
    - assets/icon/notification.png
    - assets/icon/callcenter.png
    - assets/icon/setting.png
    - assets/icon/aboutapp.png
    - assets/icon/shopping-cart.png
    - assets/icon/message.png
    - assets/icon/girlcallcenter.png
    - assets/icon/flashSaleIcon.png
    - assets/imgIllustration/IlustrasiMessage.png
    - assets/imgIllustration/IlustrasiOnBoarding1.png
    - assets/imgIllustration/IlustrasiOnBoarding2.png
    - assets/imgIllustration/IlustrasiOnBoarding3.png
    - assets/imgIllustration/IlustrasiCart.png

  fonts:
    - family: mechanic
      fonts:
        - asset: assets/fonts/mechanic.ttf
    - family: rental
      fonts:
        - asset: assets/fonts/rental.ttf
    - family: carparts
      fonts:
        - asset: assets/fonts/carparts.ttf
    - family: equipment
      fonts:
        - asset: assets/fonts/equipment.ttf

    - family: MaisonNeue
      fonts:
        - asset: assets/fonts/maison-neue-bold-italic.woff
        - asset: assets/fonts/maison-neue-bold.woff
        - asset: assets/fonts/maison-neue-book.woff
        - asset: assets/fonts/maison-neue-light-italic.woff
        - asset: assets/fonts/maison-neue-light.woff
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family: Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
    - family: Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family: Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight: 600
